# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-02 03:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_auto_20190619_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='fecha',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
