# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-02 16:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_auto_20190701_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name='registroasistencia',
            unique_together=set([('estudiante', 'fecha')]),
        ),
    ]
