# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-10 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_auto_20190702_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examen',
            options={'ordering': ['nota']},
        ),
    ]
