# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-10 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_auto_20190710_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(max_length=100)),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.Estudiante')),
            ],
        ),
        migrations.RemoveField(
            model_name='examen',
            name='fecha',
        ),
    ]
