# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-10 15:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0007_auto_20190710_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
