# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-10 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0008_permiso_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permiso',
            old_name='Estudiante',
            new_name='estudiante',
        ),
    ]
