# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-11 17:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0010_remove_examen_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='codigo',
            field=models.CharField(default=datetime.date.today, max_length=100),
        ),
    ]
