# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-11 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0011_examen_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='codigo',
        ),
    ]
