# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-12 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0012_remove_examen_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='nota',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
